// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4yxOP72Q1f-eDgQfV8CNHCy90fdkPpDc',
    appId: '1:920404916277:web:1765b017826981be1e997c',
    messagingSenderId: '920404916277',
    projectId: 'tripmate-c9850',
    authDomain: 'tripmate-c9850.firebaseapp.com',
    storageBucket: 'tripmate-c9850.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8mGyDoiLEC9ueinmF2jvA4TYJKdWD0c',
    appId: '1:920404916277:android:bfaa7546c8ecf8d11e997c',
    messagingSenderId: '920404916277',
    projectId: 'tripmate-c9850',
    storageBucket: 'tripmate-c9850.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-h3gIRWbyGOScB8Bjtrq1_RgCXW6igw',
    appId: '1:920404916277:ios:c6921a781d1d5f351e997c',
    messagingSenderId: '920404916277',
    projectId: 'tripmate-c9850',
    storageBucket: 'tripmate-c9850.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2-h3gIRWbyGOScB8Bjtrq1_RgCXW6igw',
    appId: '1:920404916277:ios:c6921a781d1d5f351e997c',
    messagingSenderId: '920404916277',
    projectId: 'tripmate-c9850',
    storageBucket: 'tripmate-c9850.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4yxOP72Q1f-eDgQfV8CNHCy90fdkPpDc',
    appId: '1:920404916277:web:70a4cabbff74f2341e997c',
    messagingSenderId: '920404916277',
    projectId: 'tripmate-c9850',
    authDomain: 'tripmate-c9850.firebaseapp.com',
    storageBucket: 'tripmate-c9850.firebasestorage.app',
  );
}
